remote_theme: "mmistakes/minimal-mistakes@4.27.3"

minimal_mistakes_skin: "contrast"

locale: "en-US"
title: "Yerim Oh"
title_separator: "|"
subtitle:
name: "Yerim Oh"
description: "Notes archive"
url: "https://ye-rim-oh.github.io"
baseurl: ""
repository: "ye-rim-oh/ye-rim-oh.github.io"
timezone: "Asia/Seoul"

logo:
masthead_title:
breadcrumbs: false
search: true
enable_copy_code_button: true

author:
  name: "Yerim Oh"
  bio:
  location: "Seoul, South Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ye-rim-oh"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ye-rim-oh"
  since: "2026"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge
permalink: /:title/

include:
  - _pages

exclude:
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - Gemfile.lock
  - vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
